apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: learning-nginx
spec:
  # deployment will take care of any pod matchingLabels app-ui
  selector:
    matchLabels:
      app: ui
  # pod template
  template:
    metadata:
      # required: define label for pod (used by higher k8s objects: Service, Deployment)
      labels:
        app: ui
    spec:
      containers:
        - name: ui-container
          image: hello-ui:latest
          imagePullPolicy: Never
          ports:
            # https://stackoverflow.com/a/65270688/2122990
            - name: ui-port
              # Port where the UI container listens (Nginx)
              containerPort: 80
