apiVersion: networking.k8s.io/v1
# Gateway doesn't use labels but Service **Name**
kind: Ingress
metadata:
  name: learning-ingress
  namespace: learning-nginx
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: svc-api
                port:
                  # Reference to service port 80 defined in 05.api-service.yaml
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-ui
                port:
                  # Reference to service port 80 defined in 03.ui-service.yaml
                  number: 80
