apiVersion: v1
# A Service provides a stable IP/DNS name for a group of dynamic Pods.
kind: Service
metadata:
  name: svc-ui
  namespace: learning-nginx
spec:
  # When traffic hits this Service it checks selector to which Pod to route the traffic
  selector:
    app: ui
  ports:
    - protocol: TCP
      targetPort: ui-port
      port: 80
      nodePort: 30123
  type: NodePort
