apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: learning
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:21.0.1
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: sso-secrets
              key: KEYCLOAK_ADMIN
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sso-secrets
              key: KEYCLOAK_ADMIN_PASSWORD
        - name: KC_PROXY
          value: "edge"
        - name: KC_HOSTNAME_URL
          value: "http://localhost:81/auth/"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_HTTP_RELATIVE_PATH
          value: "/auth"
        ports:
        - name: http
          # Port where the Keycloak container listens
          containerPort: 8080
